GROUP_ACCESS = "GroupAccess"
GCP_ACCESS_TAG = "gcp_access"
VALID_ACTION_REQUIRED_ERROR = "Valid action is required for the request."
VALID_DOMAIN_REQUIRED_ERROR = "Valid domain is require for the request."
VALID_GROUP_REQUIRED_ERROR = "Valid group is required for the request."
GRANT_ACCESS_FAILED_ERROR = "Something went wrong while adding the %s to group %s: %s"
REVOKE_ACCESS_FAILED_ERROR = "Error while removing the user from the group %s: %s"
