GROUP_ACCESS = "GroupAccess"
GCP_ACCESS_TAG = "gcp_access"
VALID_ACTION_REQUIRED_ERROR = "Valid action is required for the request."
VALID_DOMAIN_REQUIRED_ERROR = "Valid domain is require for the request."
VALID_GROUP_REQUIRED_ERROR = "Valid group is required for the request."
